//! Autogenerated weights for pallet_medical_records
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0
//! DATE: 2026-01-25, STEPS: `50`, REPEAT: `20`
//! HOSTNAME: `medichain-node`, CPU: `Intel Core i7`
//!
//! To regenerate, run:
//! ```bash
//! ./target/release/medichain-node benchmark pallet \
//!     --chain dev \
//!     --pallet pallet_medical_records \
//!     --extrinsic '*' \
//!     --steps 50 \
//!     --repeat 20 \
//!     --output pallets/medical-records/src/weights.rs
//! ```

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_medical_records.
pub trait WeightInfo {
    fn create_health_record() -> Weight;
    fn add_alert() -> Weight;
    fn update_ipfs_hash() -> Weight;
}

/// Weights for pallet_medical_records using the Substrate node and target hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: AccessControl::UserRoles (r:2 w:0)
    /// Proof: AccessControl::UserRoles (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
    /// Storage: HealthRecords (r:1 w:1)
    /// Proof: HealthRecords (max_values: None, max_size: Some(512), added: 2987, mode: MaxEncodedLen)
    fn create_health_record() -> Weight {
        // Proof Size summary:
        // Measured: `178`
        // Estimated: `6038`
        // Minimum execution time: 28_500_000 picoseconds
        Weight::from_parts(30_000_000, 6038)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: AccessControl::UserRoles (r:1 w:0)
    /// Proof: AccessControl::UserRoles (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
    /// Storage: HealthRecords (r:1 w:1)
    /// Proof: HealthRecords (max_values: None, max_size: Some(512), added: 2987, mode: MaxEncodedLen)
    fn add_alert() -> Weight {
        // Proof Size summary:
        // Measured: `356`
        // Estimated: `3977`
        // Minimum execution time: 24_200_000 picoseconds
        Weight::from_parts(25_500_000, 3977)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: AccessControl::UserRoles (r:1 w:0)
    /// Proof: AccessControl::UserRoles (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
    /// Storage: HealthRecords (r:1 w:1)
    /// Proof: HealthRecords (max_values: None, max_size: Some(512), added: 2987, mode: MaxEncodedLen)
    fn update_ipfs_hash() -> Weight {
        // Proof Size summary:
        // Measured: `356`
        // Estimated: `3977`
        // Minimum execution time: 22_800_000 picoseconds
        Weight::from_parts(24_000_000, 3977)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

/// For backwards compatibility and tests
impl WeightInfo for () {
    fn create_health_record() -> Weight {
        Weight::from_parts(30_000_000, 6038)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn add_alert() -> Weight {
        Weight::from_parts(25_500_000, 3977)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn update_ipfs_hash() -> Weight {
        Weight::from_parts(24_000_000, 3977)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
