//! Autogenerated weights for pallet_patient_identity
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0
//! DATE: 2026-01-25, STEPS: `50`, REPEAT: `20`
//! HOSTNAME: `medichain-node`, CPU: `Intel Core i7`
//!
//! To regenerate, run:
//! ```bash
//! ./target/release/medichain-node benchmark pallet \
//!     --chain dev \
//!     --pallet pallet_patient_identity \
//!     --extrinsic '*' \
//!     --steps 50 \
//!     --repeat 20 \
//!     --output pallets/patient-identity/src/weights.rs
//! ```

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_patient_identity.
pub trait WeightInfo {
    fn register_patient() -> Weight;
    fn verify_identity() -> Weight;
}

/// Weights for pallet_patient_identity using the Substrate node and target hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: AccessControl::UserRoles (r:1 w:1)
    /// Proof: AccessControl::UserRoles (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
    /// Storage: Identities (r:1 w:1)
    /// Proof: Identities (max_values: None, max_size: Some(145), added: 2620, mode: MaxEncodedLen)
    /// Storage: IdToAccount (r:1 w:1)
    /// Proof: IdToAccount (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
    fn register_patient() -> Weight {
        // Proof Size summary:
        // Measured: `142`
        // Estimated: `3610`
        // Minimum execution time: 32_500_000 picoseconds
        Weight::from_parts(34_000_000, 3610)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }

    /// Storage: AccessControl::UserRoles (r:1 w:0)
    /// Proof: AccessControl::UserRoles (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
    /// Storage: Identities (r:1 w:1)
    /// Proof: Identities (max_values: None, max_size: Some(145), added: 2620, mode: MaxEncodedLen)
    fn verify_identity() -> Weight {
        // Proof Size summary:
        // Measured: `312`
        // Estimated: `3610`
        // Minimum execution time: 18_200_000 picoseconds
        Weight::from_parts(19_000_000, 3610)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

/// For backwards compatibility and tests
impl WeightInfo for () {
    fn register_patient() -> Weight {
        Weight::from_parts(34_000_000, 3610)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }

    fn verify_identity() -> Weight {
        Weight::from_parts(19_000_000, 3610)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
