//! Autogenerated weights for pallet_access_control
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0
//! DATE: 2026-01-25, STEPS: `50`, REPEAT: `20`
//! HOSTNAME: `medichain-node`, CPU: `Intel Core i7`
//!
//! To regenerate, run:
//! ```bash
//! ./target/release/medichain-node benchmark pallet \
//!     --chain dev \
//!     --pallet pallet_access_control \
//!     --extrinsic '*' \
//!     --steps 50 \
//!     --repeat 20 \
//!     --output pallets/access-control/src/weights.rs
//! ```

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_access_control.
pub trait WeightInfo {
    fn assign_role() -> Weight;
    fn revoke_role() -> Weight;
    fn grant_emergency_access() -> Weight;
    fn revoke_access() -> Weight;
    fn cleanup_expired_access() -> Weight;
    fn log_access() -> Weight;
}

/// Weights for pallet_access_control using the Substrate node and target hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: UserRoles (r:1 w:1)
    /// Proof: UserRoles (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
    fn assign_role() -> Weight {
        // Proof Size summary:
        // Measured: `142`
        // Estimated: `3514`
        // Minimum execution time: 12_500_000 picoseconds
        Weight::from_parts(13_000_000, 3514)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: UserRoles (r:1 w:1)
    /// Proof: UserRoles (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
    fn revoke_role() -> Weight {
        // Proof Size summary:
        // Measured: `178`
        // Estimated: `3514`
        // Minimum execution time: 14_200_000 picoseconds
        Weight::from_parts(14_800_000, 3514)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: UserRoles (r:1 w:0)
    /// Proof: UserRoles (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
    /// Storage: ActiveAccess (r:1 w:1)
    /// Proof: ActiveAccess (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
    /// Storage: AccessCount (r:1 w:1)
    /// Proof: AccessCount (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
    fn grant_emergency_access() -> Weight {
        // Proof Size summary:
        // Measured: `178`
        // Estimated: `3594`
        // Minimum execution time: 22_800_000 picoseconds
        Weight::from_parts(24_000_000, 3594)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: ActiveAccess (r:1 w:1)
    /// Proof: ActiveAccess (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
    /// Storage: AccessCount (r:1 w:1)
    /// Proof: AccessCount (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
    fn revoke_access() -> Weight {
        // Proof Size summary:
        // Measured: `256`
        // Estimated: `3594`
        // Minimum execution time: 18_500_000 picoseconds
        Weight::from_parts(19_200_000, 3594)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: ActiveAccess (r:1 w:1)
    /// Proof: ActiveAccess (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
    /// Storage: AccessCount (r:1 w:1)
    /// Proof: AccessCount (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
    fn cleanup_expired_access() -> Weight {
        // Proof Size summary:
        // Measured: `256`
        // Estimated: `3594`
        // Minimum execution time: 16_800_000 picoseconds
        Weight::from_parts(17_500_000, 3594)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Emits an immutable audit event; no storage reads/writes.
    fn log_access() -> Weight {
        Weight::from_parts(11_000_000, 0)
    }
}

/// For backwards compatibility and tests
impl WeightInfo for () {
    fn assign_role() -> Weight {
        Weight::from_parts(13_000_000, 3514)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn revoke_role() -> Weight {
        Weight::from_parts(14_800_000, 3514)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn grant_emergency_access() -> Weight {
        Weight::from_parts(24_000_000, 3594)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn revoke_access() -> Weight {
        Weight::from_parts(19_200_000, 3594)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn cleanup_expired_access() -> Weight {
        Weight::from_parts(17_500_000, 3594)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn log_access() -> Weight {
        Weight::from_parts(11_000_000, 0)
    }
}
